name:  Main

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Run composer install
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --no-progress --no-suggest --dev

    - name: Run psalm 
      run: ./vendor/bin/psalm  --show-info=true

    - name: Run phpunit 
      run: ./vendor/bin/phpunit
